[pytest]
testpaths = tests
addopts =
    --alluredir=allure-results
    --tracing=retain-on-failure
    --output=test-results
    --strict-markers
    --strict-config
    -v
markers =
    ui: UI tests
    api: API tests
    smoke: Smoke tests
    regression: Regression tests
